export const LEAD_ERROR_CODES = {
  NOT_FOUND: "LEAD_NOT_FOUND",
  DUPLICATE: "LEAD_DUPLICATE",
  VALIDATION: "LEAD_VALIDATION",
  FORBIDDEN: "LEAD_FORBIDDEN",
  ARCHIVED: "LEAD_ARCHIVED",
  UNKNOWN: "LEAD_UNKNOWN",
};
