export const CONTACT_ERROR_CODES = {
  NOT_FOUND: "CONTACT_NOT_FOUND",
  DUPLICATE: "CONTACT_DUPLICATE",
  PRIMARY_REQUIRED: "CONTACT_PRIMARY_REQUIRED",
  VALIDATION: "CONTACT_VALIDATION",
  UNKNOWN: "CONTACT_UNKNOWN",
};
